### ISSUE TITLE
Hello World fails

### ISSUE THREAD

**Issue by p-i-** [Lnk2past/copperhead#12]
`pip install copperhead` followed by copy-pasting the HelloWorld example into a .ipynb notebook cell in VSCode (macOS) explodes:

```
import copperhead as cpp

hello_world_cpp = '''
#include <iostream>
void hello_world()
{
   std::cout << "Hello World!" << std::endl;
}'''

hello_world = cpp.generate('hello_world', 'void()', hello_world_cpp)

hello_world()
```

```
running install
running bdist_egg
running egg_info
writing hello_world.egg-info/PKG-INFO
writing dependency_links to hello_world.egg-info/dependency_links.txt
writing top-level names to hello_world.egg-info/top_level.txt
reading manifest file 'hello_world.egg-info/SOURCES.txt'
writing manifest file 'hello_world.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-11-x86_64/egg
running install_lib
running build_ext
building 'hello_world' extension
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/sqlite/include -I/Users/pi/gold/.venv/include -I/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c /Users/pi/gold/src/deploy/145/.copperhead_cache/hello_world/hello_world_block.cpp -o build/temp.macosx-11-x86_64-3.9/Users/pi/gold/src/deploy/145/.copperhead_cache/hello_world/hello_world_block.o
/Users/pi/gold/src/deploy/145/.copperhead_cache/hello_world/hello_world_block.cpp:36:9: warning: code will never be executed [-Wunreachable-code]
    if (PyErr_Occurred())
        ^~~~~~~~~~~~~~
/Users/pi/gold/src/deploy/145/.copperhead_cache/hello_world/hello_world_block.cpp:43:20: error: definition of variable with array type needs an explicit size or an initializer
static PyMethodDef hello_worldMethods[]
                   ^
/Users/pi/gold/src/deploy/145/.copperhead_cache/hello_world/hello_world_block.cpp:43:40: error: expected ';' after top level declarator
static PyMethodDef hello_worldMethods[]
                                       ^
                                       ;
/Users/pi/gold/src/deploy/145/.copperhead_cache/hello_world/hello_world_block.cpp:50:37: error: expected ';' after top level declarator
static PyModuleDef hello_worldmodule
                                    ^
                                    ;
1 warning and 3 errors generated.
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/unixccompiler.py", line 117, in _compile
    self.spawn(compiler_so + cc_args + [src, '-o', obj] +
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/ccompiler.py", line 910, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/spawn.py", line 91, in spawn
    raise DistutilsExecError(
distutils.errors.DistutilsExecError: command '/usr/bin/clang' failed with exit code 1

During handling of the above exception, another exception occurred:
:
(etc)
```

Please fix/doc.
This a great potential alternative to numba, but you _really_ need the HelloWorld to work!

**Comment by p-i-** [comment]
Minfail:
```
import copperhead as cpp
cpp.generate('f', 'void()', 'void f(){}')()
```

**Comment by Lnk2past** [comment]
Hi @p-i-!

Thanks for writing an issue up - I have been away from this code base for a while but I have been meaning to pick things back up. I have tons of local changes and changes in other branches - but I can try to check things out in the next day or so and see what's going on.

At a glance it looks like the code that gets generated is not compatible with clang, if you can provide the following it would be very much helpful for debugging:

* output of running `python -VV`
* output of running `clang --version`

Thanks again for the issue writeup, I will try my best to get a fix available.

**Comment by p-i-** [comment]
Sure!

```
🧢 pi@pPro18 /Users/pi 
> python -VV
Python 3.9.6 (default, Jun 29 2021, 05:25:02)
[Clang 12.0.5 (clang-1205.0.22.9)]

🧢 pi@pPro18 /Users/pi 
> clang --version
Apple clang version 13.0.0 (clang-1300.0.29.3)
Target: x86_64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

I'm figuring out how to update my macOS Python so as to bring those disparate versions into alignment. I'll report back if I fix.

I actually wrote my own Python-C++ interface years ago https://github.com/p-i-/picxx but this looks so much cleaner. So I hope you get the time to polish it. C++ is much more concise for low level mathy work.

At the moment the best option I can see for fast math is numba but I'm bumping into obstacles on that (https://github.com/numba/numba/issues/7497#issuecomment-947400939)

**Comment by p-i-** [comment]
Update:

I've just upgraded my macOS Python, and I get the same crash.

```
> python -VV
Python 3.10.0 (default, Oct 23 2021, 18:32:23) [Clang 13.0.0 (clang-1300.0.29.3)]
```

Steps were:
```
brew install pyenv
mkdir ~/test ; cd ~/test
~/.pyenv/versions/3.10.0/bin/python -m venv .venv
. .venv/bin/activate
python foo.py
```

**Comment by Lnk2past** [comment]
Awesome, thanks for all of the details! Exactly what is needed to debug :) I will see what I can do in the next day or so and will also certainly try to find some time to polish this back up!

**Comment by Lnk2past** [comment]
I was not able to reproduce this with clang v12.0.0 via a Debian image, and I refreshed the GitHub actions to test Python 3.8 and 3.9 via MacOS and those builds passed.

I need to tweak the Dockerfiles to pin to the exact versions you are using, but I am inclined to think this might be a combination of clang + MacOS causing the issue (the MacOS runners in GitHub actions use gcc).

I will need to dive a little deeper to find out how to fix the last 2 compilation errors (the first is an easy fix). I do not own a mac and so debugging may be a little harder for me at the moment.

**Comment by Lnk2past** [comment]
@p-i- I pushed 2 hotfixes, can you try installing directly from GitHub and let me know how it works?

**Comment by p-i-** [comment]
You nailed it!
🎉 🙏 🚀

**Comment by Lnk2past** [comment]
Perfect! I will look to produce a new versioned release later today :)
